dist: xenial
language: generic
group: edge
services:
  - docker
before_install:
  - wget https://dist.ballerina.io/downloads/2201.0.2/ballerina-2201.0.2-swan-lake-linux-x64.deb
  - sudo dpkg -i ballerina*.deb
  - bal version
  - sudo bal dist update
script:
  - bal pull ballerinax/twitter
  - bal run main.bal
  - bal search apache
